### ISSUE TITLE
CatalogEndpoint created is not correct

### ISSUE THREAD

**Issue by cmoulliard** [redhat-microservices/lab_springboot-openshift#2]
This forge command `$FORGE_PATH/forge -e "rest-generate-endpoints-from-entities --targets org.cdservice.model.*"` generates a CatalogEndpoint where some problems are reported here :  

- CatalogEndpoint doesn't include @Component annotation which is required by CXF to register the REST endpoints
- CatalogEndpoint include @Stateless annotation which is not required as we don't use JavaEE libs
- PersistentUnit is still included and should be removed `	@PersistenceContext(unitName = "spring-boot-pu")`

![screenshot 2017-06-09 11 33 28](https://user-images.githubusercontent.com/463790/26969869-84ff7dc0-4d07-11e7-97a1-7e2a1f9ddcfa.png)

**Comment by metacosm** [comment]
This should be solved with the last version of the code but you need to specify the appropriate generator: `rest-generate-endpoints-from-entities --targets org.cdservice.model.* --generator SPRING_BOOT_JPA_ENTITY`.
